In [2]:
import numpy as np

In [31]:
x = np.arange(0, 9)
print('Array from 0 to 9:')
print(x)

Array from 0 to 9:
[0 1 2 3 4 5 6 7 8]


In [35]:
array = x
array = np.broadcast_to(True, (3, 3))
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [48]:
x = np.arange(1, 10)
x[x%2 == 1] = -1
print(x)

[-1  2 -1  4 -1  6 -1  8 -1]


In [50]:
x = array_2 = np.arange(10)
print("1D array:")
print(x)

array_2 = x.reshape(2, 5)
print("2D array:")
print(array_2)

1D array:
[0 1 2 3 4 5 6 7 8 9]
2D array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [68]:
a = np.arange(6)
print(a)
b = np.arange(6,12)
print(b)
c = np.dot(a, b)
sum = np.sum(c)
print(sum)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
145
